### ISSUE TITLE
Graphic glitches on AMD GPUs

### ISSUE THREAD

**Issue by giovanniberti** [owodzeg/V4Hero#63]
On AMD GPUs the game sometimes glitches.

Some screenshots, courtesy of @the_rising_dragon on Discord:

![](https://cdn.discordapp.com/attachments/414593167631974401/857244193544863784/Captura_de_pantalla_26.png)
![](https://cdn.discordapp.com/attachments/414593167631974401/857244210586845224/Captura_de_pantalla_24.png)
![](https://cdn.discordapp.com/attachments/414593167631974401/857244223853690901/Captura_de_pantalla_25.png)

Owocek also provided an example to reproduce the glitches here:

![](https://cdn.discordapp.com/attachments/606575623363887158/851909329312940052/unknown.png)

~Where commenting line 19 reproduces the problem 100% of the time, while leaving it uncommented manages to make the problem disappear.~
EDIT: See [here](https://github.com/OwocekTV/V4Hero/issues/63#issuecomment-866845567), the issue isn't that reproducible

**Comment by RugnirViking** [comment]
I'll add that "reproduces the problem 100% of the time" and "leaving it uncommented manages to make the problem disappear." isn't quite true - we've both been unable to reproduce the problem with the line and encountered it without that line at times

**Comment by OwocekTV** [comment]
It's pretty random which is painful to make a minimal example, sometimes it glitches 100% of the time, and sometimes nothing for over 100 runs.

**Comment by giovanniberti** [comment]
[This](https://en.sfml-dev.org/forums/index.php?topic=14110.msg98922#msg98922) could a solution

**Comment by OwocekTV** [comment]
<img width="641" alt="V4Hero_V5Mzwoy9AO" src="https://user-images.githubusercontent.com/13590668/123538483-699bf880-d735-11eb-882c-1aa1838c61da.png">
Issue also happens most of the time for me when entering the world map and changing location selection.
Re-entering world map (causing it to re-load the sprites) makes the corruption go to other backgrounds, while the firstly selected background remains intact.

<img width="641" alt="V4Hero_YtIKc80X4g" src="https://user-images.githubusercontent.com/13590668/123538532-a8ca4980-d735-11eb-96c6-d0c4823ed934.png">
<img width="641" alt="V4Hero_HQLzHg9Ik2" src="https://user-images.githubusercontent.com/13590668/123538535-aec02a80-d735-11eb-9fe3-f225379eaac3.png">
Using a debug function to save all currently loaded textures (texture to image, then saveToFile) reveals that the textures are already corrupted when they are loaded, before they are displayed. So the game here displays what the texture provides, so the corruption must occur somewhere during load.

<img width="453" alt="explorer_L6XReUbr9Q" src="https://user-images.githubusercontent.com/13590668/123538591-02327880-d736-11eb-8729-3ee7bea17c3c.png">

Responsing to @giovanniberti 's solution above, adding window.resetGLStates() every frame did not solve the issue. It is not a rendering issue.

**Comment by OwocekTV** [comment]
It appears the texture corruption issue only appears when we use the `=` operator on PSprites.

On my small tool I was running a lot of tests to verify what is causing the problem and at which point the problem occurs.
Vector reallocation/storing PSprites in vector doesn't seem to be a problem.

Problem occured when I was directly assigning PSprites to each other, as in `A = B;`.


Note, that it affects both sides for some reason?
Examples:
`PSprite = Vector[x];`
`Draw PSprite;`
Result: corruption.

`PSprite = Vector[x];`
`Draw Vector[x];`
Result: corruption.

`Draw Vector[x];`
Result: works correctly.

We might be close to solving it.
Having that said, @giovanniberti 's theory could be correct.

<img width="394" alt="Discord_01gcyOewHA" src="https://user-images.githubusercontent.com/13590668/124918179-0774aa80-dff5-11eb-96a9-4e9aeb15c6af.png">

**Comment by OwocekTV** [comment]
Considering everything that was written above, I am pretty sure that the issue was directly assigning PSprites to each other. On Debug compiler preset, the game was popping out a lot of opengl errors, which certainly didn't say well about the state of how we handle graphics.

Having that said, [recent commits](https://github.com/OwocekTV/V4Hero/compare/a743644652f5...2d62f7ade808) that I've made are introducing a new TextureManager class that stores all textures in one safe place without them being directly copied around when passing PSprites.

When tested on a AMD GPU system, the world map worked as intended, without visual glitches. This can be only a "lucky" day where the issue doesn't appear, so we'll keep testing and hopefully this will be the final nail to this bug's coffin.

**Comment by owodzeg** [comment]
confirmed to be resolved on AMD systems
