### ISSUE TITLE
Crash after starting the first mission

### ISSUE THREAD

**Issue by Gaypatapon** [owodzeg/V4Hero#95]
So i have compiled patafour and then i start a new save, i think it has to do something with the two errors in vs code here

 CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.28/Modules/FetchContent.cmake:1331 (message):The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
not set.  The policy's OLD behavior will be used.  When using a URL
download, the timestamps of extracted files should preferably be that of
the time of extraction, otherwise code that depends on the extracted
contents might not be rebuilt if the URL changes.  The OLD behavior
preserves the timestamps from the archive instead, but this is usually not
what you want.  Update your project to the NEW behavior or specify the
DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
robustness issue. 

and,

 CMake Deprecation Warning at build/_deps/json-src/CMakeLists.txt:1 (cmake_minimum_required):Compatibility with CMake < 3.5 will be removed from a future version of
CMake.

Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions. 

i followed your delisted video on compiling patafour and i still dont know what i did wrong

**Comment by Gaypatapon** [comment]
I have a asus laptop with intel core i5 and nvidia geforce 930mx,and my OS is windows 10

**Comment by Hemlol19** [comment]
This was a bug in the multithread rhythm system that owocek had already fixed

**Comment by Gaypatapon** [comment]
> This was a bug in the multithread rhythm system that owocek had already fixed

Well is there a way to fix it?

**Comment by Hemlol19** [comment]
> > This was a bug in the multithread rhythm system that owocek had already fixed
> 
> Well is there a way to fix it?

Wait until the repo gets updated

**Comment by Gaypatapon** [comment]
ok

**Comment by owodzeg** [comment]
CMake warning has nothing to do with how the mission is being loaded

Mission crashes are being investigated, commit https://github.com/owodzeg/V4Hero/commit/6162963c694b9a22db9d167e9ff573224af632c5 deal with some of these but I'm not sure if that'll solve all of them

**Comment by GaypataponALT** [comment]
> CMake warning has nothing to do with how the mission is being loaded
> 
> Mission crashes are being investigated, commit [6162963](https://github.com/owodzeg/V4Hero/commit/6162963c694b9a22db9d167e9ff573224af632c5) deal with some of these but I'm not sure if that'll solve all of them

Hello this is my new acc, also I'm happy that you will fix som of the bugs relating to the mission crash

**Comment by owodzeg** [comment]
no longer relevant, mission system was completely reworked
