### ISSUE TITLE
Severe bugs found by CppCheck

### ISSUE THREAD

**Issue by Nemoumbra** [owodzeg/V4Hero#97]
![image](https://github.com/owodzeg/V4Hero/assets/62447396/a64d502b-8a78-4feb-b1ea-dbc125e81a5e)

The rest are not too bad for a hotfix to be required, but these are just the worst. I got `SIGILL` because of that:
```c++
Pon* PonRegistry::GetPonByID(int id)
{
    for (int i = 0; i < pons.size(); i++)
    {
        if (i == id)
        {
            return &pons[i];
        }
    }

    cout << "PonRegistry could not find the appropriate Pon" << endl;
}
```

**Comment by owodzeg** [comment]
fixed in 2c1d865
